# Generated by Django 5.1.7 on 2026-03-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="section",
            field=models.CharField(
                choices=[
                    ("Сегодня", "Сегодня"),
                    ("Вчера", "Вчера"),
                    ("Ранее", "Ранее"),
                ],
                default="Сегодня",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=30)),
                ("time", models.CharField(max_length=5)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="core.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "time"],
                "unique_together": {("teacher", "day", "time")},
            },
        ),
    ]
