# Generated by Django 5.1.7 on 2026-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_notification_section_teacheravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_file",
            field=models.FileField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
